
.PHONY:	all run run-pc clean

all: main.nes main

main.nes: main.c
	cl65 -Oir -t nes main.c tileset.s -o $@

run: main.nes
	fceux main.nes
	@# remove files generated by FCEUX
	@rm -f main.cdl main.nes.ram.nl

main: main.c pc-port.c
	gcc main.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o $@

run-pc: main
	./main

clean:
	rm -f main.nes main.o tileset.o main
