
.PHONY:	all run run-pc run-web clean

all: main.nes main web/main.html

main.nes: main.c tileset.s tileset.chr
	cl65 -Ois -t nes main.c tileset.s -o $@

run: main.nes
	fceux main.nes
	@# remove files generated by FCEUX
	@rm -f main.cdl main.nes.ram.nl

main: main.c pc-port.c
	gcc main.c -Wall -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o $@

run-pc: main
	./main

web/main.html: main.c pc-port.c tileset.png
	mkdir -p web
	emcc -o $@ -O2 main.c -Wall ~/raylib/src/libraylib.a -I. -I$(HOME)/raylib/src/ -L. -L$(HOME)/raylib/src/libraylib.a -s USE_GLFW=3 --shell-file $(HOME)/raylib/src/minshell.html -DPLATFORM_WEOM_WEB -s ASYNCIFY --preload-file tileset.png

run-web: web/main.html
	emrun web/main.html

clean:
	rm -rf main.nes main.o tileset.o main web/
