
.PHONY:	all nes run linux run-pc web run-web clean

all: nes linux web

main.nes: main.c tileset.s tileset.chr
	cl65 -Ois -t nes main.c tileset.s -o $@

nes: main.nes

run: nes
	fceux main.nes
	@# remove files generated by FCEUX
	@rm -f main.cdl main.nes.ram.nl

main: main.c pc-port.c
	gcc main.c -Wall -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o $@

linux: main

run-pc: linux
	./main

web/main.html: main.c pc-port.c tileset.png
	mkdir -p web
	emcc -o $@ -O2 main.c -Wall $(HOME)/raylib/src/libraylib.a -I. -I$(HOME)/raylib/src/ -L. -L$(HOME)/raylib/src/libraylib.a -s USE_GLFW=3 --shell-file $(HOME)/raylib/src/minshell.html -DPLATFORM_WEOM_WEB -s ASYNCIFY --preload-file tileset.png

web: web/main.html

run-web: web
	emrun web/main.html

clean:
	rm -rf main.nes main.o tileset.o main web/